// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFSeFsrRsYURmX5hZWmMJwG2D7O73sz-o',
    appId: '1:525890137745:web:18807998cba7259afc5930',
    messagingSenderId: '525890137745',
    projectId: 'appmovil-f68d8',
    authDomain: 'appmovil-f68d8.firebaseapp.com',
    storageBucket: 'appmovil-f68d8.appspot.com',
    measurementId: 'G-63YMK02V7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7dXCXiAMABJLwXSGyUjHTjn5QV-8cCdI',
    appId: '1:525890137745:android:1b1deb4bb3b8bf92fc5930',
    messagingSenderId: '525890137745',
    projectId: 'appmovil-f68d8',
    storageBucket: 'appmovil-f68d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDtL7ZsVz8AkTVZoRKee4y6KO6bTorgYw',
    appId: '1:525890137745:ios:132e2a5f99ef5bd7fc5930',
    messagingSenderId: '525890137745',
    projectId: 'appmovil-f68d8',
    storageBucket: 'appmovil-f68d8.appspot.com',
    iosBundleId: 'pe.edu.upeu.asistenciaAppn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDtL7ZsVz8AkTVZoRKee4y6KO6bTorgYw',
    appId: '1:525890137745:ios:132e2a5f99ef5bd7fc5930',
    messagingSenderId: '525890137745',
    projectId: 'appmovil-f68d8',
    storageBucket: 'appmovil-f68d8.appspot.com',
    iosBundleId: 'pe.edu.upeu.asistenciaAppn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFSeFsrRsYURmX5hZWmMJwG2D7O73sz-o',
    appId: '1:525890137745:web:f4647a641846a78ffc5930',
    messagingSenderId: '525890137745',
    projectId: 'appmovil-f68d8',
    authDomain: 'appmovil-f68d8.firebaseapp.com',
    storageBucket: 'appmovil-f68d8.appspot.com',
    measurementId: 'G-TTB8TQTZG6',
  );

}